#Spring
server.port=9010
server.servlet.context-path=/improsvita/api

#Spring Data JPA and databases
spring.datasource.url=jdbc:postgresql://localhost:9011/local_database
spring.datasource.username=william
spring.datasource.password=secret123
spring.jpa.hibernate.ddl-auto=create-drop