#Spring
server.port=9010
server.servlet.context-path=/improsvita/api

#Spring Data JPA and databases
spring.datasource.url=jdbc:postgresql://localhost:9011/local_database
spring.datasource.username=william
spring.datasource.password=secret123
spring.jpa.hibernate.ddl-auto=create-drop

#JWT
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
# logging.level.org.springframework.security=DEBUG